name: setup xmake
description: Set up a xmake environment and add it to the PATH
author: OpportunityLiu
branding:
  icon: play
  color: green

inputs:
  xmake-version:
    required: true
    default: latest
    description: The version to use. Should be a semver range or 'latest'. Or use pr@{pr_number} to select a pr, use branch@{branch_name} to select a branch

runs:
  using: 'node12'
  main: 'dist/index.js'
  