name: Test

on: 
- push

jobs:
  build:
    strategy:
      matrix:
        os: 
        - ubuntu-latest
        - windows-latest
        - macOS-latest

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - uses: xmake-io/github-action-setup-xmake@master
      with:
        xmake-version: latest
    - name: test
      run: |
        xmake create -P test
        xmake build -P test
        xmake run -P test
