name: test

on: 
- push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - uses: xmake-io/github-action-setup-xmake@master
      with:
        xmake-version: branch@master
    - uses: xmake-io/github-action-setup-xmake@master
      with:
        xmake-version: latest
    - name: Run tests
      run: |
        xmake create -P test
        xmake build -P test
        xmake run -P test
